// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using riwgy.Models;

namespace riwgy.Migrations
{
    [DbContext(typeof(RiwgyDbContext))]
    partial class RiwgyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("riwgy.Model.UrlMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Riwgy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Riwgy")
                        .IsUnique();

                    b.ToTable("UrlMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
